# Databricks Apps Configuration for NextLevel RAG API
# This configuration deploys the FastAPI application to Databricks Apps serverless platform

# Command to start the application
command:
  - "uvicorn"
  - "app.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

# Environment Variables Configuration
env:
  # ============================================================================
  # AUTO-INJECTED BY DATABRICKS (No need to define)
  # ============================================================================
  # - DATABRICKS_HOST: Your workspace URL
  # - DATABRICKS_WORKSPACE_ID: Workspace identifier
  # - DATABRICKS_APP_PORT: Port to bind (defaults to 8000)

  # ============================================================================
  # SECRETS (Sensitive Data - Use valueFrom)
  # ============================================================================

  # Databricks authentication token
  - name: DATABRICKS_TOKEN
    valueFrom: secret/nextlevel-api/databricks-token

  # API key for endpoint authentication
  - name: API_KEY
    valueFrom: secret/nextlevel-api/api-key

  # ============================================================================
  # DATABRICKS JOB IDs
  # ============================================================================

  - name: INGEST_JOB_ID
    value: "0"

  - name: SUMMARIZATION_JOB_ID
    value: "0"

  - name: QUESTION_GENERATION_JOB_ID
    value: "0"

  # ============================================================================
  # UNITY CATALOG CONFIGURATION
  # ============================================================================

  - name: CATALOG_NAME
    value: "databricks_rag_dev"

  - name: SCHEMA_NAME
    value: "nextlevel-rag"

  - name: SQL_WAREHOUSE_ID
    value: "6c563112651348b1"

  # ============================================================================
  # VOLUME CONFIGURATION
  # ============================================================================

  - name: VOLUME_RAW_PDFS
    value: "raw_pdfs"

  - name: VOLUME_SCREENSHOTS
    value: "screenshots"

  # ============================================================================
  # TABLE CONFIGURATION
  # ============================================================================

  - name: TABLE_CHUNKS
    value: "chunks_embedded"

  - name: TABLE_REGISTRY
    value: "pdf_registery"

  - name: TABLE_SCREENSHOTS
    value: "page_screenshots"

  # ============================================================================
  # VECTOR SEARCH CONFIGURATION
  # ============================================================================

  - name: VECTOR_SEARCH_ENDPOINT
    value: "heineken-vdb"

  - name: VECTOR_INDEX_NAME
    value: "chunks_embedded_index"

  # ============================================================================
  # MODEL CONFIGURATION
  # ============================================================================

  - name: EMBEDDING_MODEL
    value: "databricks-gte-large-en"

  # ============================================================================
  # APPLICATION SETTINGS
  # ============================================================================

  - name: ALLOWED_ORIGINS
    value: "*"

  - name: MAX_FILE_SIZE_MB
    value: "1000"

  - name: ALLOWED_EXTENSIONS
    value: ".pdf"

# ============================================================================
# RESOURCE PERMISSIONS
# ============================================================================
# Define access permissions to Databricks resources

resources:
  # Secret scope access (read-only)
  - name: nextlevel-api-secrets
    permission: CAN_READ
    secret:
      scope: nextlevel-api

  # SQL Warehouse access for Unity Catalog queries
  - name: nextlevel-sql-warehouse
    permission: CAN_USE
    sql_warehouse:
      id: "6c563112651348b1"

  # Vector Search endpoint access
  - name: nextlevel-vector-search
    permission: CAN_USE
    serving_endpoint:
      name: "heineken-vdb"
